#
# Generated by SM2Gen version:0.9(20Jan2025) Chameleon version:4.5.4 On Python:3.12.3 at 2025-06-29 08:53:20 
#
#
# Routines to be edited by the developer to provide content and validation for parameters
# and provison of the control data for table(s)
#
use esmith::util;
use esmith::util::network;
use esmith::ConfigDB::UTF8;
use esmith::AccountsDB::UTF8;
use esmith::NetworksDB::UTF8;
use esmith::HostsDB;
use esmith::DomainsDB::UTF8;
use Data::Validate::IP qw(is_ipv4 is_ipv6);


use constant FALSE => 0;
use constant TRUE  => 1;

our @EXPORT_OK = qw(get_current_webmail_status);

#The most common ones - open DB when required.
our $cdb; 
my $adb; 
my $ndb; 
my $hdb; 
my $ddb; 

#our $ui = SrvMngr::Controller::EmailsettingsCustomUI->new();

# in Emailsettings-Custom.pm
my $_ui;
sub ui {
    my $db = shift // $cdb // esmith::ConfigDB::UTF8->open;
    $_ui ||= SrvMngr::Controller::EmailsettingsCustomUI->new(db => $db);
    return $_ui;
}

#The most common ones - you might want to use these if you need to make sure that the DB is refreshed.
#$cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
#$adb = esmith::AccountsDB::UTF8->open() || die("Couldn't open Accounts db");
#$ndb = esmith::NetworksDB->open() || die("Couldn't open Network db");
#$hdb = esmith::HostsDB::UTF8->open() 	  || die("Couldn't open Hosts db");
#$ddb = esmith::DomainsDB::UTF8->open()  || die("Couldn't open Domains db");


# Validation routines - parameters for each panel

	sub validate_FRONT {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		# Validation for each field 
		my $ret = '';
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub validate_ACC {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		# Validation for each field 
		my $ret = '';
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub validate_FIL {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		# Validation for each field 
		my $ret = '';
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub validate_REC {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		# Validation for each field 
		my $ret = '';
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub validate_DEL {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		# Validation for each field 
		my ($result,$ret) = ('') x 2;
		CHECKS: {
			$ret = $c->validate_ip_or_blank($c->param('DelegateMailServer'));
			$c->app->log->info("$c->param('DelegateMailServer') $ret");
			if ($ret ne 'ok') {
				#$result = $c->l($ret);
				last CHECKS;
			}

			$ret = $c->validate_smarthost($c->param('SMTPSmartHost'));
			if ($ret ne 'ok') {
				#$result = $c->l($ret);
				last CHECKS;
			}

			$ret = $c->nonblank_if_smtpauth($c->param('SMTPSmartHost'));
			if ($ret ne 'ok') {
				#$result = $c->l($ret);
				last CHECKS;
			}

			$ret = $c->nonblank_if_smtpauth($c->param('SMTPAUTHPROXY_Userid'));
			if ($ret ne 'ok') {
				#$result = $c->l($ret);
				last CHECKS;
			}

			$ret = $c->nonblank_if_smtpauth($c->param('SMTPAUTHPROXY_Passwd'));
			if ($ret ne 'ok') {
				#$result = $c->l($ret);
				last CHECKS;
			}

			$ret = $c->change_settings_delivery();
			if ($ret ne 'ok') {
				#$result = $ret;
				last CHECKS;
			}
			#$result = '';
		}
		# $ret now contains the first error or the null (success) message
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}


# Get singleton data for each panel

	sub get_data_for_panel_FRONT {
		# Return a hash with the fields required which will be loaded into the shared data 
		my $c = shift;
		my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
		my %ret = (
			'Data1'=>'Data for FRONT', #Example
			# fields from Inputs in FRONT $fields['FRONT']
			'fetchmailmethod' => $cdb->get_prop('fetchmail', 'Method'),
			
		);
		return %ret;
	}

	sub get_data_for_panel_ACC {
		# Return a hash with the fields required which will be loaded into the shared data 
		my $c = shift;
		my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
		my %ret = (
			# fields from Inputs in ACC $fields['ACC']
			'fetchmailmethod' => $cdb->get_prop('fetchmail', 'Method'),
		);
		return %ret;
	}

	sub get_data_for_panel_FIL {
		# Return a hash with the fields required which will be loaded into the shared data 
		my $c = shift;
		my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
		my %ret = (
			# fields from Inputs in FIL $fields['FIL']
			'virusstatus' => $c->get_virus_status(),
			'spamstatus'      => $cdb->get_prop('spamassassin', 'status'),
			'spamsensitivity' => $cdb->get_prop('spamassassin', 'Sensitivity', 'medium'),
			'spamtaglevel'    => $cdb->get_prop('spamassassin', 'TagLevel') || '0',
			'spamrejectlevel' => $cdb->get_prop('spamassassin', 'RejectLevel') || '0',
			'spamsortspam'      => $cdb->get_prop('spamassassin', 'SortSpam'),
			'spamsubjecttag'    => $cdb->get_prop('spamassassin', 'SubjectTag'),
			'spamsubject'       => $cdb->get_prop('spamassassin', 'Subject'),
		);
		return %ret;
	}

	sub get_data_for_panel_REC {
		# Return a hash with the fields required which will be loaded into the shared data 
		my $c = shift;
		my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
		my %ret = (
			'Data1'=>'Data for REC', #Example
			# fields from Inputs in REC $fields['REC']
			'fetchmailmethod'       => $cdb->get_prop('fetchmail', 'Method'),
			'freqoffice'            => $cdb->get_prop('fetchmail', 'FreqOffice'),
			'freqoutside'           => $cdb->get_prop('fetchmail', 'FreqOutside'),
			'freqweekend'           => $cdb->get_prop('fetchmail', 'FreqWeekend'),
			'secondarymailserver'   => $cdb->get_prop('fetchmail', 'SecondaryMailServer'),
			'secondarymailaccount'  => $cdb->get_prop('fetchmail', 'SecondaryMailAccount'),
			'secondarymailpassword' => $cdb->get_prop('fetchmail', 'SecondaryMailPassword'),
			'specifyheader'         => get_secondary_mail_use_envelope(),
			'secondarymailenvelope' => $cdb->get_prop('fetchmail', 'SecondaryMailEnvelope'),
		);
		return %ret;
	}

	sub get_data_for_panel_DEL {
		# Return a hash with the fields required which will be loaded into the shared data 
		my $c = shift;
		my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
		my %ret = (
			# fields from Inputs in DEL $fields['DEL']
			'emailunknownuser'      => $cdb->get_value('EmailUnknownUser') || '"returntosender',
			'delegatemailserver'    => $cdb->get_value('DelegateMailServer'),
			'smtpsmarthost'         => $cdb->get_prop('postfix','SMTPSmartHost'),
			'smtpauthproxystatus'   => $cdb->get_prop('postfix', 'SMTPSmartHostStatus') || 'disabled',
			'smtpauthproxyuserid'   => $cdb->get_prop('postfix', 'SMTPSmartHostUserid') || '',
			'smtpauthproxypassword' => $cdb->get_prop('postfix', 'SMTPSmartHostPasswd') || '',
      'smtpauthproxypeerport' => $cdb->get_prop('postfix', 'SMTPSmartHostPeerPort') || '',
		);
		return %ret;
	}

# Get control data for table(s)
# Return hash with values from row in which link clicked on table

	sub get_selected_FRONT {
		my $c = shift;
		my $selected = shift; #Parameter is name of selected row.
		my $is_new_record = shift; #Indicates new record required (defaults)
		my %ret = ();
		#gather the values here
		return %ret;
	}

	sub get_selected_ACC {
		my $c = shift;
		my $selected = shift; #Parameter is name of selected row.
		my $is_new_record = shift; #Indicates new record required (defaults)
		my %ret = ();
		#gather the values here
		return %ret;
	}

	sub get_selected_FIL {
		my $c = shift;
		my $selected = shift; #Parameter is name of selected row.
		my $is_new_record = shift; #Indicates new record required (defaults)
		my %ret = ();
		#gather the values here
		return %ret;
	}

	sub get_selected_REC {
		my $c = shift;
		my $selected = shift; #Parameter is name of selected row.
		my $is_new_record = shift; #Indicates new record required (defaults)
		my %ret = ();
		#gather the values here
		return %ret;
	}

	sub get_selected_DEL {
		my $c = shift;
		my $selected = shift; #Parameter is name of selected row.
		my $is_new_record = shift; #Indicates new record required (defaults)
		my %ret = ();
		#gather the values here
		return %ret;
	}


#after sucessful modify or create or whatever and submit then perfom (if the params validate)

	sub perform_FRONT {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		my $ret = '';
		my $db = $cdb; #maybe one of the others
		my $dbkey = 'ChangeThis';
		# To make it write to DB as comment, delete this (regex) string in each if statement "TRUE\) \#copy or perform with value: .* e.g."
		
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub perform_ACC {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		my $ret = '';
		my $db = $cdb; #maybe one of the others
		my $dbkey = 'ChangeThis';
		#$c->app->log->info("pop:".$c->param('POPAccess'));
        if (!ui()->apply_option('pop_110_995',$c->param('POPAccess'))) {$c->app->log->info($c->param('POPAccess')."Not written to DB");}
        ui()->apply_option('imap_143',$c->param('IMAPAccess'));
        ui()->apply_option('webmail',$c->param('WebMail'));
		$ret = $c->change_settings_access();
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub perform_FIL {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		my $ret = '';
		my $db = $cdb; #maybe one of the others
		my $dbkey = 'ChangeThis';
		# To make it write to DB as comment, delete this (regex) string in each if statement "TRUE\) \#copy or perform with value: .* e.g."
		$ret = $c->change_settings_filtering();
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub perform_REC {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		my $ret = '';
		my $db = $cdb; #maybe one of the others
		my $dbkey = 'ChangeThis';
		# Update the DB entries as specified in the ui structure.
		ui()->apply_option('smtp_25',$c->param('SMTPAuth'));
		ui()->apply_option('smtps_465',$c->param('sSMTPAuth'));
		ui()->apply_option('submission_587',$c->param('uSMTPAuth'));
		# Do the legacy rest.
		$ret = $c->change_settings_reception();
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}

	sub perform_DEL {
		my $c = shift;
		my $mai_data = shift; #Data hash as parameter
		my $ret = '';
		my $db = $cdb; #maybe one of the others
		my $dbkey = 'ChangeThis';
		# To make it write to DB as comment, delete this (regex) string in each if statement "TRUE\) \#copy or perform with value: .* e.g."
		$ret = $c->change_settings_delivery();
		if ($ret eq '') {$ret = 'ok';}
		return $ret;
	}


sub create_link{
	# WIP
	my ($c,$route, $panel, $index) = @_;
	my $link = "$route?trt=$panel&Selected=$index";
	return $link;
}

sub get_virus_status {
    my ($c, $localise) = @_;
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    my $status = $cdb->get_prop("qpsmtpd", 'VirusScan') || 'disabled';
    return $localise ? $c->localise_status($status) : $status;
} ## end sub get_virus_status

sub get_spam_status {
    my ($c, $localise) = @_;
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    my $status = $cdb->get_prop('spamassassin', 'status') || 'disabled';
    return $localise ? $c->localise_status($status) : $status;
} ## end sub get_spam_status

sub localise_status {
    my ($c, $status) = @_;
    return $c->l($status eq 'enabled' ? $c->l('ENABLED') : $c->l('DISABLED'));
}

sub get_db_prop {
    my ($c, $item, $prop, $default) = @_;
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    return $cdb->get_prop($item, $prop) || $default;
}

sub get_value {
    my $c    = shift;
    my $item = shift;
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    return $cdb->get_value($item) || '';
} ## end sub get_value

sub get_emailunknownuser_status {
    my ($c, $localise) = @_;
    my $options = $c->get_emailunknownuser_options();
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    my $val = $cdb->get_value('EmailUnknownUser') || "returntosender";
    return $localise ? $c->l($options->{$val}) : $val;
} ## end sub get_emailunknownuser_status

sub get_patterns_status {
    my ($c, $localise) = @_;
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    my $status = $cdb->get_prop("qpsmtpd", 'PatternsScan') || 'disabled';
    return $localise ? $c->localise_status($status) : $status;
} ## end sub get_patterns_status

sub adjust_patterns {
    my $c        = shift;
    my @selected = @{ $c->every_param('BlockExecutableContent') };
    $pattern_db = esmith::ConfigDB::UTF8->open("mailpatterns");
    foreach my $pattern ($pattern_db->get_all_by_prop(type => "pattern")) {
        my $status
            = (grep $pattern->key eq $_, @selected)
            ? 'enabled'
            : 'disabled';
        $pattern->set_prop('Status', $status);
    } ## end foreach my $pattern ($pattern_db...)
    $pattern_db->reload;
    return scalar @selected;
} ## end sub adjust_patterns


sub get_current_webmail_status {
	my $webmail_current_menu_entry = ui()->get_current_menu_option('webmail');
	return $webmail_current_menu_entry->{value};
}

sub get_retrieval_opt {
    my $c = shift;
	my $cdb = esmith::ConfigDB::UTF8->open()   || die("Couldn't open config db");
    return $cdb->get("SystemMode")->value eq "servergateway-private"
        ? [ $c->l('mai_MULTIDROP') => 'multidrop' ]
        : [
        [ $c->l('mai_STANDARD')  => 'standard' ],
        [ $c->l('mai_ETRN')      => 'etrn' ],
        [ $c->l('mai_MULTIDROP') => 'multidrop' ]
        ];
} ## end sub get_retrieval_opt

sub get_emailunknownuser_options {
    my $c                = shift;
    my $accounts         = esmith::AccountsDB::UTF8->open_ro();
    my %existingAccounts = (
        'admin'          => $c->l("mai_FORWARD_TO_ADMIN"),
        'returntosender' => $c->l("mai_RETURN_TO_SENDER")
    );

    foreach my $account ($accounts->get_all) {
        next if $account->key eq 'everyone';

        if ($account->prop('type') =~ /(user|group|pseudonym)/) {
            $existingAccounts{ $account->key } = $c->l("mai_FORWARD_TO") . " " . $account->key;
        }
    } ## end foreach my $account ($accounts...)
    return (\%existingAccounts);
} ## end sub get_emailunknownuser_options

sub get_emailunknownuser_opt {
    my $c        = shift;
    my $accounts = esmith::AccountsDB::UTF8->open_ro();
    my @existingAccounts
        = ([ $c->l("mai_FORWARD_TO_ADMIN") => 'admin' ], [ $c->l("mai_RETURN_TO_SENDER") => 'returntosender' ]);

    foreach my $account ($accounts->get_all) {
        next if $account->key eq 'everyone';

        if ($account->prop('type') =~ /(user|group|pseudonym)/) {
            push @existingAccounts, [ $c->l("mai_FORWARD_TO") . " " . $account->key => $account->key ];
        }
    } ## end foreach my $account ($accounts...)
    return (\@existingAccounts);
} ## end sub get_emailunknownuser_opt

sub get_patterns_opt {
    my $c = shift;
    my $pattern_db = esmith::ConfigDB::UTF8->open("mailpatterns");
    my @options;

    foreach my $pattern ($pattern_db->get_all_by_prop(type => "pattern")) {
        my %props = $pattern->props;
        push @options, [ $props{'Description'} => $pattern->key ];
    }
    return \@options;
} ## end sub get_patterns_opt

sub get_patterns_current_opt {
    my $c = shift;
    my @selected;
    my $pattern_db = esmith::ConfigDB::UTF8->open("mailpatterns");


    foreach my $pattern ($pattern_db->get_all_by_prop(type => "pattern")) {
        my %props = $pattern->props;
        push @selected, $pattern->key if ($props{'Status'} eq 'enabled');
    }
    return \@selected;
} ## end sub get_patterns_current_opt

sub get_spam_level_options {
    return [ 0 .. 20 ];
}

sub get_spam_sensitivity_opt {
    my $c = shift;
    return [
        [ $c->l('mai_VERYLOW')  => 'verylow' ],
        [ $c->l('mai_LOW')      => 'low' ],
        [ $c->l('mai_MEDIUM')   => 'medium' ],
        [ $c->l('mai_HIGH')     => 'high' ],
        [ $c->l('mai_VERYHIGH') => 'veryhigh' ],
        [ $c->l('mai_CUSTOM')   => 'custom' ]
    ];
} ## end sub get_spam_sensitivity_opt

sub fetchmail_freq {
    my $c = shift;
    return [
        [ $c->l('mai_NEVER')      => 'never' ],
        [ $c->l('mai_EVERY5MIN')  => 'every5min' ],
        [ $c->l('mai_EVERY15MIN') => 'every15min' ],
        [ $c->l('mai_EVERY30MIN') => 'every30min' ],
        [ $c->l('mai_EVERYHOUR')  => 'everyhour' ],
        [ $c->l('mai_EVERY2HRS')  => 'every2hrs' ]
    ];
} ## end sub fetchmail_freq

sub display_multidrop {
    my $status = $cdb->get_prop('fetchmail', 'status') || 'disabled';

    # XXX FIXME - WIP
    # Only display ETRN/multidrop settings if relevant
    # To do this, we need an "Show ETRN/multidrop settings" button
    # in standard mode.
    # return ($status eq 'enabled');
    return 1;
} ## end sub display_multidrop

sub change_settings_reception {
    my $c = shift;
    $cdb = esmith::ConfigDB::UTF8->open || die "Couldn't open config db";
    my $FetchmailMethod      = ($c->param('FetchmailMethod') || 'standard');
    my $FetchmailFreqOffice  = ($c->param('FreqOffice')      || 'every15min');
    my $FetchmailFreqOutside = ($c->param('FreqOutside')     || 'everyhour');
    my $FetchmailFreqWeekend = ($c->param('FreqWeekend')     || 'everyhour');
    my $SpecifyHeader        = ($c->param('SpecifyHeader')   || 'off');
    my $fetchmail = $cdb->get('fetchmail') || $cdb->new_record("fetchmail", { type => "service", status => "disabled" });

    if ($FetchmailMethod eq 'standard') {
        $fetchmail->set_prop('status', 'disabled');
        $fetchmail->set_prop('Method', $FetchmailMethod);
    } else {
        $fetchmail->set_prop('status',              'enabled');
        $fetchmail->set_prop('Method',              $FetchmailMethod);
        $fetchmail->set_prop('SecondaryMailServer', $c->param('SecondaryMailServer'))
            unless ($c->param('SecondaryMailServer') eq '');
        $fetchmail->set_prop('FreqOffice',           $FetchmailFreqOffice);
        $fetchmail->set_prop('FreqOutside',          $FetchmailFreqOutside);
        $fetchmail->set_prop('FreqWeekend',          $FetchmailFreqWeekend);
        $fetchmail->set_prop('SecondaryMailAccount', $c->param('SecondaryMailAccount'))
            unless ($c->param('SecondaryMailAccount') eq '');
        $fetchmail->set_prop('SecondaryMailPassword', $c->param('SecondaryMailPassword'))
            unless ($c->param('SecondaryMailPassword') eq '');

        if ($SpecifyHeader eq 'on') {
            $fetchmail->merge_props('SecondaryMailEnvelope' => $c->param('SecondaryMailEnvelope'));
        } else {
            $fetchmail->delete_prop('SecondaryMailEnvelope');
        }
    } ## end else [ if ($FetchmailMethod eq...)]

	#Note -successful return from signal-event is 1 (true)
    my $status = system("/sbin/e-smith/signal-event", "email-update");   
	if (!$status == 0 ) { 
        return $c->l('mai_ERROR_UPDATING_CONFIGURATION',$status);
    }
    return '';
} ## end sub change_settings_reception

sub change_settings_delivery {
    my ($c) = shift;
    $cdb = esmith::ConfigDB::UTF8->open || die "Couldn't open config db";
    my $EmailUnknownUser = ($c->param('EmailUnknownUser') || 'returntosender');
    $cdb->set_prop('postfix','SMTPSmartHost',      $c->param('SMTPSmartHost'));
    $cdb->set_value('DelegateMailServer', $c->param('DelegateMailServer'));
    $cdb->set_value('EmailUnknownUser',   $EmailUnknownUser);
    my $proxy = $cdb->get('postfix');
    my %props = $proxy->props;

    for (qw(Userid Passwd Status PeerPort)) {
        $props{"SMTPSmartHost$_"} = $c->param("SMTPAUTHPROXY_$_");
    }
    $proxy->merge_props(%props);

	#Note -successful return from signal-event is 1 (true)
    my $status = system("/sbin/e-smith/signal-event", "email-update");   
	if (!$status == 0 ) { 
        return $c->l('mai_ERROR_UPDATING_CONFIGURATION',$status);
    }
    return '';
} ## end sub change_settings_delivery

sub change_settings_access {
    my $c = shift;
    $cdb = esmith::ConfigDB::UTF8->open || die "Couldn't open config db";
    
	#Note -successful return from signal-event is 1 (true)
    my $status = system("/sbin/e-smith/signal-event", "email-update");   
	if (!$status == 0 ) { 
        return $c->l('mai_ERROR_UPDATING_CONFIGURATION',$status);
    }
    return '';
} ## end sub change_settings_access

sub change_settings_filtering {
    my $c = shift;
    $cdb = esmith::ConfigDB::UTF8->open || die "Couldn't open config db";
    my $virus_status = ($c->param('VirusStatus') || 'disabled');
    $cdb->set_prop("qpsmtpd", 'VirusScan', $virus_status);

    for my $param (
        qw(
        status
        Sensitivity
        TagLevel
        RejectLevel
        SortSpam
        Subject
        SubjectTag)
        )
    {
        $cdb->set_prop('spamassassin', $param, $c->param("Spam$param"));
    } ## end for my $param (qw( status...))
    my $patterns_status = $c->adjust_patterns() ? 'enabled' : 'disabled';
    $cdb->set_prop("qpsmtpd", 'PatternsScan', $patterns_status);

	#Note -successful return from signal-event is 1 (true)
    my $status = system("/sbin/e-smith/signal-event", "email-update");   
	if (!$status == 0 ) { 
        return $c->l('mai_ERROR_UPDATING_CONFIGURATION',$status);
    }
    return '';
} ## end sub change_settings_filtering

sub nonblank_if_smtpauth {
    my ($c, $value) = @_;
    return 'ok' unless ($c->param("SMTPAUTHPROXY_Status") eq 'enabled');
    return ($value =~ /\S+/) ? 'ok' : $c->l('mai_VALIDATION_SMTPAUTH_NONBLANK');
}

sub get_secondary_mail_use_envelope {
    $cdb = esmith::ConfigDB::UTF8->open || die "Couldn't open config db";
    my $use_envelope = $cdb->get_prop('fetchmail', 'SecondaryMailEnvelope');
    if (defined $use_envelope) {
        return ('on');
    } else {
        return ('off');
    }
} ## end sub get_secondary_mail_use_envelope 

sub validate_smarthost {
    my $c        = shift;
    my $smarthost = shift;
    return ('ok') if ($smarthost =~ /^(\S+\.\S+)$/);
    return ('ok') if ($smarthost eq '');
    return "mai_INVALID_SMARTHOST";
} ## end sub validate_smarthost


sub validate_ip_or_blank {
  my ($c,$ip) = @_;

  return 'ok' if $ip eq '';

  return 'ok' if is_ipv4($ip) || is_ipv6($ip);

  return "mai_INVALID_DELEGATE";
}

sub get_localised_menu_items {
    my ($c, $svc) = @_;

    my $select = ui()->get_menu_options($svc);
    return [] unless $select && ref($select) eq 'ARRAY';

    my @localised;

    for my $item (@$select) {
        next unless ref($item) eq 'HASH';
        
        my %copy = %$item;
        if (defined $copy{label} && length $copy{label}) {
             $copy{label} = $c->l($copy{label});
         }
        
        # Convert hashref to arrayref for select_field
        push @localised, [ $copy{label}, $copy{value} ];
    }

    return \@localised;
}
1;
